NewProjected/Controllers/TentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using NewProjected.Models;

namespace NewProjected.Controllers
{
    public class TentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tents
        public ActionResult Index()
        {
            return View(db.Tents.ToList());
        }

        // GET: Tents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tents tents = db.Tents.Find(id);
            if (tents == null)
            {
                return HttpNotFound();
            }
            return View(tents);
        }

        // GET: Tents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Pic")] Tents tents)
        {
            if (ModelState.IsValid)
            {
                byte[] Pic = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Pic"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        Pic = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }
                tents.Pic = Pic;
                tents.Deposit = tents.PriceEachDay / 2;
                db.Tents.Add(tents);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tents);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult NewBooking(BookingItems booking)
        {
            if (ModelState.IsValid)
            {
                if (booking.PickupDate < booking.ReturnDate)
                {
                    var price = db.Tents.Where(l => l.TentId == booking.ItemId && l.TentName == booking.ItemName).Select(p => p.PriceEachDay).FirstOrDefault();
                    if (price==0) 
                    {
                        price = db.Vehicles.Where(l => l.VehicleID == booking.ItemId && l.CarName == booking.ItemName).Select(p => p.PricePerDay).FirstOrDefault();
                    }
                    if (price==0) 
                    {
                        price = db.Venue.Where(l => l.VenueID == booking.ItemId && l.Name == booking.ItemName).Select(p => p.PricePerDay).FirstOrDefault();
                    }

                    booking.Rental = price*(booking.ReturnDate.Day - booking.PickupDate.Day);
                    booking.Deposit = booking.Rental / 2;
                    booking.UserID = User.Identity.Name;
                    db.BookingItems.Add(booking);
                    db.SaveChanges();
                    return RedirectToAction("BookingIndex", "Vehicles");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "The return date cannot be lesser than pick up date !");
                    return View(booking);
                }
            }

            return View(booking);
        }
        [Authorize]
        // GET: Tents/Edit/5
        public ActionResult NewBooking(int itemId,string itemName)
        {
            BookingItems items = new BookingItems();
            items.ItemId = itemId;
            items.ItemName = itemName;
            return View(items);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tents tents = db.Tents.Find(id);
            if (tents == null)
            {
                return HttpNotFound();
            }
            return View(tents);
        }

        // POST: Tents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TentId,TentName,NumPoles,diposit,PriceEachDay,Pic")] Tents tents)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tents).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tents);
        }

        // GET: Tents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tents tents = db.Tents.Find(id);
            if (tents == null)
            {
                return HttpNotFound();
            }
            return View(tents);
        }

        public FileContentResult UserPhotos(int tentId)
        {
            if (tentId == 0)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");

            }
            else
            {
                var pic = db.Tents.Where(k=>k.TentId==tentId).Select(k=> k.Pic).FirstOrDefault();
                return new FileContentResult(pic, "image/jpeg");

            }
        }

        // POST: Tents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tents tents = db.Tents.Find(id);
            db.Tents.Remove(tents);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewProjected/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using NewProjected.Models;

namespace NewProjected.Controllers
{
    public class VenuesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Venues
        public ActionResult Index()
        {
            return View(db.Venue.ToList());
        }

        // GET: Venues/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venue venue = db.Venue.Find(id);
            if (venue == null)
            {
                return HttpNotFound();
            }
            return View(venue);
        }

        // GET: Venues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Pic")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                byte[] Pic = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files["Pic"];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        Pic = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }
                venue.Pic = Pic;
                venue.Deposit = venue.PricePerDay/2;
                db.Venue.Add(venue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(venue);
        }

        public FileContentResult UserPhotos(int venueId)
        {
            if (venueId == 0)
            {
                string fileName = HttpContext.Server.MapPath(@"~/Images/noImg.png");

                byte[] imageData = null;
                FileInfo fileInfo = new FileInfo(fileName);
                long imageFileLength = fileInfo.Length;
                FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                BinaryReader br = new BinaryReader(fs);
                imageData = br.ReadBytes((int)imageFileLength);

                return File(imageData, "image/png");

            }
            else
            {
                var pic = db.Venue.Where(k => k.VenueID == venueId).Select(k => k.Pic).FirstOrDefault();
                return new FileContentResult(pic, "image/jpeg");

            }
        }

        // GET: Venues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venue venue = db.Venue.Find(id);
            if (venue == null)
            {
                return HttpNotFound();
            }
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VenueID,Name,Location,occupantsNumber,PricePerDay,Pic")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venue).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venue);
        }

        // GET: Venues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venue venue = db.Venue.Find(id);
            if (venue == null)
            {
                return HttpNotFound();
            }
            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venue venue = db.Venue.Find(id);
            db.Venue.Remove(venue);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewProjected/Views/Venues/Create.cshtml
@model NewProjected.Models.Venue

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Venues", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.occupantsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.occupantsNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.occupantsNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        
            <div class="form-group">
                @Html.LabelFor(model => model.Pic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <h4>Select Picture</h4>
                    <input type="file" name="Pic" id="Pic" accept=".jpg" />
                </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewProjected/Views/Venues/Delete.cshtml
@model NewProjected.Models.Venue

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Venue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.occupantsNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.occupantsNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NewProjected/Views/Venues/Details.cshtml
@model NewProjected.Models.Venue

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Venue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.occupantsNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.occupantsNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VenueID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NewProjected/Views/Venues/Edit.cshtml
@model NewProjected.Models.Venue

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VenueID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.occupantsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.occupantsNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.occupantsNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewProjected/Views/Venues/Index.cshtml
@model IEnumerable<NewProjected.Models.Venue>

@{
    ViewBag.Title = "Index";
}

    <style>
        div.gallery {
            margin: 5px;
            border: 1px solid #ccc;
            float: left;
           width:230;
            background-color:mediumpurple;
        }

            div.gallery:hover {
                border: 1px solid #777;
            }

        div.desc {
            text-align: left;
        }
    </style>
<h2>Index</h2>



<table class="table">

    @foreach (var item in Model)
    {
        <tr>

            <div class="gallery">
                <a target="_blank" href="img_5terre.jpg">


                    @{
                        var base64 = Convert.ToBase64String(item.Pic);
                        var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                    <a href='@Url.Action("Details", new { id = item.VenueID })'>
                        <img src='@imgsrc' height="150" width="230" />
                    </a>

                </a>
                <div class="desc">Tent name :  @Html.DisplayFor(modelItem => item.Name)</div>
                <div class="desc">Deposit amount : R @Html.DisplayFor(modelItem => item.Deposit)</div>
                <div class="desc">Cost per day : R @Html.DisplayFor(modelItem => item.PricePerDay)</div>
                <div class="desc">Location :  @Html.DisplayFor(modelItem => item.Location)</div>
                <button class="btn-success">
                    <a href="@Url.Action("NewBooking", "Tents", new { itemId = item.VenueID, itemName = item.Name })">
                        Add Booking
                       
                        </a>
                </button>
            </div>
        </tr>
    }

</table>